# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = ["laptop", "gaming", "gpu_drivers/nvidia", "gpu_drivers/intel"]

[managers.system]
items = ["powernotd-bin"]
