[managers.system]
items = [
  "linux-zen",
  "linux-zen-headers",
  "lld",
  "llvm",
  "fish",
  "zsh",
  "fzf",
  "udisks2",
  "parted",
  "git",
  "zip",
  "unzip",
  "clang",
  "gcc",
  "vim",
  "neovim",
  "stow",
  "trash-cli",
]
