[managers.system]
items = [
    "lsd",
    "fish",
    "zsh",
    "fzf",
    "udisks2",
    "parted",
    "git",
    "zip",
    "unzip",
    "clang",
    "gcc",
    "vim",
    "neovim",
    "stow",
    "trash-cli",
]
