imports = ["wayland", "display_manager"]

[managers.system]
items = [
  "hyprland",
  "hyprlock",
  "hypridle",
  "hyprswitch",
  "--mflags '--nocheck' gtk4-layer-shell",
  "xdg-desktop-portal",
  "xdg-desktop-portal-gtk",
  "xdg-desktop-portal-hyprland",
  "hyprpicker",
  "hyprcursor",
  "polkit-gnome",
]
