[env]
ENV_VARIABLE = "value"

[GTK]
# Whether to use the dark theme
application_prefer_dark_theme = true

# GTK theme name
theme_name = "catppuccin-mocha-lavender-standard+default"

[commands]
# The command used to reboot the system
reboot = ["systemctl", "reboot"]

# The command used to shut down the system
poweroff = ["systemctl", "poweroff"]

[appearance]
# The message that initially displays on startup
greeting_msg = "Welcome back!"
