
# #######################################################################################
#
#
#  ███████╗████████╗ █████╗ ██████╗ ███████╗██╗  ██╗██╗██████╗ 
#  ██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██╔══██╗
#  ███████╗   ██║   ███████║██████╔╝███████╗███████║██║██████╔╝
#  ╚════██║   ██║   ██╔══██║██╔══██╗╚════██║██╔══██║██║██╔═══╝ 
#  ███████║   ██║   ██║  ██║██║  ██║███████║██║  ██║██║██║     
#  ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝     
#                                                              
# by Nekoy
# #######################################################################################

command_timeout = 1000
right_format= """
$cmd_duration\
$time\
"""

# Sets user-defined palette
palette = "catppuccin_mocha"

[username]
show_always = true
format = '[\[[$user](lavender bold)\]](bold surface2) '

[hostname]
ssh_only = true
disabled = false
format = '[\[\]](bold blue) [\[[$hostname](bold blue)\]](bold surface2) '

[cmd_duration]
format = '[\[[$duration](italic yellow)\]](bold surface2)'

[time]
disabled = false
format = ' [\[[$time](overlay1)\]](bold surface2)'
time_format = "%R"
utc_time_offset = "local"

[character]
success_symbol = "[-❯](text)"
error_symbol = "[[](red) -❯](text)"
vimcmd_symbol = "[[](green) -❯](text)"
vimcmd_visual_symbol = "[[](lavender) -❯](text)"
vimcmd_replace_symbol = "[[](red) -❯](text)"
vimcmd_replace_one_symbol = "[[](red) -❯](text)"

[directory]
read_only = '[]'
truncation_length = 10
truncate_to_repo = true # truncates directory to root folder if in github repo
format = '[\[[$path](bold overlay1)\]](bold surface2) [$read_only]($read_only_style bold)'

[git_status]
format = '([\[$all_status$ahead_behind\]](bold surface2) )'
stashed = "[${count}*](green)" 
modified = "[${count}+](yellow)" 
deleted =  "[${count}-](red)" 
conflicted =  "[${count}~](red)" 
ahead = "⇡${count}"
behind = "⇣${count}"
untracked = "[${count}?](blue)" 
staged = "[${count}+](green)" 

[git_branch]
format = '[\[[$branch(:$remote_branch)](bold lavender)\]](bold surface2) '

# use fe
[package]
format = '[\[[󰏖 $version](bold peach)\]](bold surface2) '

[lua]
format = '[\[[󰢱 $version](bold blue)\]](bold surface2) '

[rust]
format = '[\[[ $version](red bold)\]](bold surface2)'

[c]
format = '[\[[ $version](bold blue)\]](bold surface2)'

[python]
format = '[\[[ $version](bold blue)\]](bold surface2)'

[java]
format = '[\[[ $version](bold red dimmed)\]](bold surface2)'

[golang]
format = '[\[[󰟓 $version](bold cyan)\]](bold surface2)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
