#!/usr/bin/env bash

sudo cp ~/.config/rebos/system_configs/greetd.toml /etc/greetd/config.toml
sudo cp ~/.config/rebos/system_configs/hyprland.conf /etc/greetd/hyprland.conf
sudo cp ~/.config/rebos/system_configs/regreet.toml /etc/greetd/regreet.toml
sudo cp ~/.config/rebos/system_configs/greeter.jpg /usr/share/backgrounds/greeter.jpg 
sudo cp ~/.config/rebos/system_configs/grub /etc/default/grub
sudo cp -r ~/.config/rebos/system_configs/catppuccin-mocha-grub-theme /usr/share/grub/themes 

if pacman -Qs nvidia-dkms > /dev/null 2>&1; then
    sudo cp ~/.config/rebos/system_configs/nvidia_environment /etc/environment
fi

if pacman -Qs firewalld > /dev/null 2>&1; then
  sudo systemctl disable firewalld --now
  sudo pacman -Rns firewalld
  sudo pacman -S ufw
  sudo systemctl enable ufw --now
fi

if pacman -Qs virt-manager > /dev/null 2>&1; then
  sudo usermod -aG libvirt $USER
  sudo usermod -aG kvm $USER
  sudo usermod -aG video $USER
  
  sudo systemctl enable libvirtd.service --now

  sudo virsh net-autostart default > /dev/null
fi

if pacman -Qs auto-cpufreq > /dev/null 2>&1; then
  sudo systemctl enable auto-cpufreq --now
fi

if pacman -Qs syncthing > /dev/null 2>&1; then
  sudo systemctl enable syncthing@$USER
fi
