#!/usr/bin/env bash

if pacman -Qs firewalld > /dev/null 2>&1; then
  sudo systemctl disable firewalld --now
  sudo pacman -Rns firewalld
  sudo pacman -S ufw
  sudo systemctl enable ufw --now
fi

if pacman -Qs virt-manager > /dev/null 2>&1; then
  sudo usermod -aG libvirt $USER
  sudo usermod -aG kvm $USER
  sudo usermod -aG video $USER
  
  sudo systemctl enable libvirtd.service --now

  sudo virsh net-autostart default > /dev/null
fi

if pacman -Qs auto-cpufreq > /dev/null 2>&1; then
  sudo systemctl enable auto-cpufreq --now
fi

if pacman -Qs syncthing > /dev/null 2>&1; then
  sudo systemctl enable syncthing@$USER
fi
